### ISSUE TITLE
To use 'Promisify' to simplify the code

### ISSUE THREAD

**Issue by luizdesign** [zalando/tailor#172] opened 2017-08-23 14:19 UTC
Continue the discuss about use promisify started in #171 (https://github.com/zalando/tailor/pull/171#issuecomment-324324643)

**Comment by addityasingh** [comment] 2017-08-24 08:08
@vigneshshanmugam Based on our discussion earlier on the PR for this issue [here](https://github.com/zalando/tailor/pull/157), I remember that the `util.promisify` library had some performance issue because of prototype chaining. Do you think it still makes sense to https://github.com/ljharb/util.promisify library?

**Comment by vigneshshanmugam** [comment] 2017-08-24 08:42
@addityasingh Lets reopen the PR and add the remaining changes if you are interested in taking it forward. Most projects are using it these days.

**Comment by addityasingh** [comment] 2017-08-24 08:57
@luizdesign If you want to work on it, please go ahead. Else, I can take it up

**Comment by addityasingh** [comment] 2017-08-24 08:57
Duplicate of https://github.com/zalando/tailor/issues/153

**Comment by luizdesign** [comment] 2017-08-24 11:56
@addityasingh  I didn't start work on it yet, I'm working to finish the changes to #171

**Comment by addityasingh** [comment] 2017-08-25 11:49
Cool. Let me make the changes quickly then

**Comment by vigneshshanmugam** [comment] 2017-09-01 12:44
You guys wanna take it up?

**Comment by addityasingh** [comment] 2017-09-02 10:51
@vigneshshanmugam Please have a look now

**Closed** 2017-09-04 11:40 UTC
